### ISSUE TITLE
`check-token.html` says "Valid" in green for expired tokens.

### ISSUE THREAD

**Issue by lgarron** [jpchase/ExperimentalFramework#15]
Screenshot:

<img width="408" alt="screen shot 2016-10-03 at 11 35 22" src="https://cloud.githubusercontent.com/assets/248078/19049081/c252b034-895d-11e6-8b20-c73859f80938.png">

I think this should show either "Invalid" or "Expired" instead.

If "Valid" is only meant to refer to e.g. the signature, then it should say something like "Signature valid".

(Motivated by https://github.com/GoogleChrome/permission.site/pull/26#issuecomment-251187863)

**Comment by beaufortfrancois** [comment]
See https://github.com/jpchase/OriginTrials/pull/16
