### ISSUE TITLE
Web bluetooth token not working

### ISSUE THREAD

**Issue by ajitam** [jpchase/ExperimentalFramework#21]
Hi, I just receive my token and I can't get it to work.

The only reason I can think of is that my domain is not running on default https port.

To explain: In sign-up form I stated my domain: `https://some-domain.com`. And now I'm running my experiment on `https://some-domain.com:12345/experiment`. I 'm not that familiar with token to know if this can be a problem.

thx, matija

**Comment by ajitam** [comment]
Ok, I just opened default HTTPS port (`443`) and it works. Is there a way you can "change" my token to custom port?

**Comment by clelland** [comment]
For the record, the form at http://bit.ly/OriginTrialSignup will accept a port in the origin field. You can eter something like

```
https://some-domain.com:12345
```

as the origin, and we'll generate a token for that origin.

There's no way to "change" a token, once issued -- it's just a string -- but we can certainly issue a new one, and you can just ignore any renewal reminder emails for the original one.
