### ISSUE TITLE
Automate/Formalize the OT signup process

### ISSUE THREAD

**Issue by pyalot** [jpchase/ExperimentalFramework#22]
Currently the way to get OT tokens is to fill out a google docs survey and then wait for a human to eventually read your request and send you an email.

I'd suggest that this be changed in the following fashion:

* provide a real website/service
* automate token issuance
* document the OT trial token API so it can be automated by website authors

**Comment by owencm** [comment]
We're currently working on this but it's taking a little longer than we had originally expected! We'll have a console online providing this function as soon as possible!

**Comment by jpchase** [comment]
Closing as we now have a website that provides fully automated self-service: https://developers.chrome.com/origintrials

At this time, we do not intend to provide an API for web developers to automate registration and token generation.
