### ISSUE TITLE
WebVR origin trial enables navigator.getVRDisplays but Promise never returns

### ISSUE THREAD

**Issue by jbaicoianu** [jpchase/ExperimentalFramework#24]
I've received my Origin Trial code and have added it to my page, but I'm not sure it's working as intended.  I'm running Chrome 56.0.2924.18 dev (64-bit) in Windows 10, with a Rift+Touch.

Some observations:
 - As expected, on a page without an Origin Trial token navigator.getVRDisplays() is undefined
 - On a page with an Origin Trial token, the navigator.getVRDisplays() promise is never fulfilled, nor is the error callback called
 - This affects the WebVR samples as well, eg https://webvr.info/samples/00-hello-webvr.html

Am I jumping the gun here, and when we say M56 it actually means this will only be available once the 56.x branch hits the stable channel?

**Comment by jpchase** [comment]
No, when referring to M56, it means the version of the browser, not the date/stable channel.

From your description, it sounds as if the Origin Trial token is working correctly, in that navigator.getVRDisplays() becomes available (where it was undefined without the token).

This sounds like a problem specific to WebVR. I think you should look for help from the WebVR experts. Try one of the following:
https://webvr.info/
https://developers.google.com/web/fundamentals/vr/

**Comment by jbaicoianu** [comment]
I guess I am jumping the gun, https://blog.chromium.org/2016/12/introducing-webvr-api-in-chrome-for.html seems to imply that WebVR in M56 is *ONLY* for the Daydream platform, and that desktop and other mobile devices will have to wait until M57.

This should probably be communicated clearly somewhere, it's been a frustrating day for me.
