### ISSUE TITLE
Update available-trials.md with WebVR (For Chrome M59+)

### ISSUE THREAD

**Issue by mckaydavis** [jpchase/ExperimentalFramework#28]
The [Origin Trials signup page](http://bit.ly/OriginTrialSignup) has an option `WebVR (For Chrome M59+)` that is not listed or described on the [available-trials.md](https://github.com/jpchase/OriginTrials/blob/gh-pages/available-trials.md).

The original [Intent to Experiment](https://groups.google.com/a/chromium.org/forum/m/#!topic/blink-dev/zGAzqfi0e00/discussion
) post was updated by @toji on 2017-03-15 requested that the trial be extended through M58 and a new trial would be started.  I assume this new trial corresponds to the `WebVR (For Chrome M59+)` option listed in the signup form feature selection drop-down.

From my confirmation email, the WebVR (For Chrome M59+) trial will end on Oct 17, 2017.

It would be helpful if the available-trials.md reflected this information.

**Comment by mckaydavis** [comment]
Here's the corresponding [Intent to Continue Experimenting: WebVR](https://groups.google.com/a/chromium.org/forum/#!topicsearchin/blink-dev/intent$20to$20experiment/blink-dev/OnZVNSGwEFU) post by Brandon Jones (@toji)

**Comment by jpchase** [comment]
The list has been updated. Thanks for the reminder!
