### ISSUE TITLE
add "Web Locks" and "EME Extension - Policy Check" to `available-trials.md`

### ISSUE THREAD

**Issue by cvan** [jpchase/ExperimentalFramework#40]
The list of experiments in [`available-trials.md`](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/available-trials.md#current-experimental-features) does not include **`Web Locks`** nor **`EME Extension - Policy Check`**, but they are both options on the [Origin-Trial Signup Page](https://docs.google.com/forms/d/1OTvEk-VfavyKkMxef0Tvs0RFycl9NNu1vdg3FrqJhX8/viewform?edit_requested=true).

<hr>

![List of experiments in this repo](https://user-images.githubusercontent.com/203725/37632734-eaf44816-2bac-11e8-9aad-50d4fea752bc.png)

![List of experiments on signup page](https://user-images.githubusercontent.com/203725/37632635-7523c6a2-2bac-11e8-835b-4eaee16a3eaf.png)

**Comment by clelland** [comment]
Thanks -- it looks like we need to do a better job of keeping these in sync.

As of today, the list should just be:
* WebVR (For Chrome M62+)
* Media Capabilities
* Web Locks
* macOS Native Echo Cancellation

(And as of tomorrow, we should remove Media Capabilities as well.) The remaining trials should all be moved to the completed-trials.md doc.

**Comment by clelland** [comment]
The list is up-to-date now, as of commit https://github.com/GoogleChrome/OriginTrials/commit/e5f0548bf56909303400d1c27bb69d98bd041a2b
