### ISSUE TITLE
WebXR is not listed on Token Sign-Up Form

### ISSUE THREAD

**Issue by cvan** [jpchase/ExperimentalFramework#46]
1. In the [`available-trials.md` document](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/available-trials.md#current-experimental-features), notice both _WebXR_ and _WebVR_ are listed:
    ![image](https://user-images.githubusercontent.com/203725/39547432-71805e52-4e0c-11e8-9536-c9d9745eb375.png)
2. Published on Monday, April 30, [this Chromium Blog post](https://blog.chromium.org/2018/04/chrome-67-beta-webxr-origin-trial.html) also mentions the _WebXR_ Origin Trial:
    ![image](https://user-images.githubusercontent.com/203725/39547494-a05b5dc6-4e0c-11e8-8e45-b83029ce29c2.png)
3. Load the [Token Sign-Up Form](https://docs.google.com/forms/d/e/1FAIpQLSfO0_ptFl8r8G0UFhT0xhV17eabG-erUWBDiKSRDTqEZ_9ULQ/viewform), and notice _WebXR_ is missing from the `Feature` drop-down menu choices:
    ![image](https://user-images.githubusercontent.com/203725/39547325-1bdbf592-4e0c-11e8-8d19-48b819ba3273.png)

**Comment by arobins** [comment]
Fixed.
