### ISSUE TITLE
WebVR support no longer working in Chrome 69

### ISSUE THREAD

**Issue by dustinkerstein** [jpchase/ExperimentalFramework#48]
Is this intended? Everything is working great in Chrome 68 and earlier.

**Comment by clelland** [comment]
Yes, this is intended. The WebVR trial was timed to end on 2018-09-11, coinciding with the release of Chrome 69 (and as such, the OT code for it has been removed from Chrome as of M69).

I believe that the VR team intends to replace the API itself with WebXR, which is also an experimental API. (There was a bit of a hiccup with that trial, but the team has filed an intent to continue experimenting, so we hope to have signups re-enabled for that trial this week.)

**Comment by arpu** [comment]
how can i generate a WebVr 1.1 trial token now?

**Comment by jpchase** [comment]
WebVR 1.1 is no longer available as a trial, so it's not possible to get a trial token. WebVR 1.1 remains available behind a flag, by enabling chrome://flags/#enable-experimental-web-platform-features.

As in the earlier comment, WebXR is intended as the replacement for WebVR. WebXR is currently available as an origin trial.
