### ISSUE TITLE
Enabling an origin trial in WebPageTest

### ISSUE THREAD

**Issue by rviscomi** [jpchase/ExperimentalFramework#53]
Is it possible to enable an origin trial in a lab tool like WebPageTest, for example by starting Chrome with a command line flag or similar, specifically for origins outside of our control? This would be useful for A/B testing and transparency tools that rely on WPT like the HTTP Archive.

My understanding of opting in to an OT is that each origin receives a token which is included in the HTML as a `meta` tag or response header. But is there a way to do this for an arbitrary origin on an ad hoc basis just for synthetic testing purposes?

cc @igrigorik

**Comment by arobins** [comment]
If you have control of the browser process, I think you can use the --enable-blink-features flag to enable an OT feature for all origins.

**Comment by clelland** [comment]
That's true -- Origin Trial features in Chrome are just Blink features, and can be enabled unconditionally (for *all* origins) through the command line, or (often) through chrome://flags.

There isn't a way to turn them on and off for individual origins without tokens, though. You might be able to do it with some combination of setting your own token-signing key, minting your own tokens for those origins, and injecting them into the responses with an extension, but I don't know if anyone has actually tried all of that.

**Comment by rviscomi** [comment]
Is there necessarily a 1:1 command line flag for each OT feature? I'm specifically interested in the Layout Stability OT.

**Comment by clelland** [comment]
Not necessarily 1:1, but the mapping is all controlled by [this file](https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/runtime_enabled_features.json5). In this case, the feature is called LayoutJankAPI, so `--enable-blink-features=LayoutJankAPI` should work.

**Comment by rviscomi** [comment]
That's perfect thanks!
