### ISSUE TITLE
Why send renewal notices if the Renew button is disabled?

### ISSUE THREAD

**Issue by cawerkenthin** [jpchase/ExperimentalFramework#58]
I received a link to renew.  I click it, log in and the renew button is disabled.

**Comment by jpchase** [comment]
The renew button is usually disabled when feedback has not been provided on the trial. You can find more information about renewals in the developer guide:
https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md#12-how-do-i-renew-a-token-that-is-about-to-expirehas-expired

The reason for sending the renewal notice is to remind developers to renew and provide feedback on the trial. It's expected that that the renew button will often be disabled when a renewal notice is sent.

**Comment by cawerkenthin** [comment]
[cid:eb96ae59-d3de-4874-92c6-4a771ea29674]
And where would that button be?


[cid:7cb5cd20-1d59-4232-839c-be6a2e5c1809]

Art Werkenthin
President
RISC, Inc.
The Foundation of Your Learning Ecosystem

[cid:a085c4c3-88b3-4ca8-8001-aa26c1dbc576]<https://www.facebook.com/RISCInc> [cid:2a16b1f1-c444-4726-9a07-512d7b0698e3] <https://twitter.com/RISC_Inc>   [cid:ab75429f-e07d-492b-a6d2-eaace8cd084f] <https://www.linkedin.com/company/riscinc/>

[cid:ab2e028a-8e0c-4811-ab14-572ff5bfcd9c]<https://risc-inc.com/blog>

________________________________

[cid:9b419d82-0466-4617-a433-cda5950085c9] 281-480-7910
[cid:74b8131d-d803-4f86-a270-80167ca9c068]  artw@risc-inc.com<mailto:trinad@risc-inc.com>
[cid:d9f3cc1f-7dc6-40b0-84db-bcaef667640c]  risc-inc.com<https://risc-inc.com/>
[cid:4b84a4c4-858f-4081-befb-7fac10d9a08d]  718 FM 1959, Ste A, Houston, TX 77034


________________________________

**Comment by jpchase** [comment]
As in the support thread, there was a configuration issue with the Allow Sync XHR in Page Dismissal trial, so that feedback wasn't enabled. That was causing the Feedback button to be hidden.

I believe that should resolve this issue. Please re-open if there's more to address.
