### ISSUE TITLE
Are multi-subdomain tokens still restricted to default ports?

### ISSUE THREAD

**Issue by domenic** [jpchase/ExperimentalFramework#63]
https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md#13-i-have-multiple-testingstaging-domains-or-subdomains-that-are-programmatically-generated-do-i-need-to-request-a-token-for-every-subdomain doesn't mention any port restrictions. Since people sometimes use non-default ports when developing, e.g. `https://mybox.corp.google.com:8443`, it would be good to know whether this works.

**Comment by jpchase** [comment]
Yes, non-default ports are supported. When registering, you just need to specify the port as part of the origin. 

If you [check a generated token](https://googlechrome.github.io/OriginTrials/check-token.html), you can see that port is specified. Tokens are always generated with a port in the origin, it's just that the OT dashboard will fill in the default, if not provided by the user.

**Comment by domenic** [comment]
Got it. So wildcard subdomains does not imply wildcard ports, and thus you'd need a separate origin trial token if you wanted to do local dev on `:8443` or similar.

**Comment by yogeshmn** [comment]
Can we update the documentation with information about default ports and how to request a token for non-default ports? We should probably also include it on the token registration page for clarity. I spent a couple of hours trying to debug why the token won't work on my local dev instance only to realize that the token is tied to the default port and won't work with my app which uses port 26001.
