### ISSUE TITLE
Can a third party opt into an Origin Trial?

### ISSUE THREAD

**Issue by KenjiBaheux** [jpchase/ExperimentalFramework#7]
Hi,

I was wondering if a third party can opt into an origin trial in the following situations:
1. a cross origin third party script in the main document.
2. a cross origin third party script in a cross origin iframe.
3. a cross origin third party script in a cross origin iframe in a cross origin iframe in a...

My guesses:
- Situation 1: No. Reason: a dynamically inserted meta tag would not allow access to an OT feature.
- Situation 2: Depends. Yes (?) if OT opt-in is not limited to top level document/origin, No otherwise (the third party would have its key as a meta tag in the iframe or as a header on the iframe resource). The OT feature would be available in the iframe context.
- Situation 3: similar to 2. The OT feature would be available in the nested iframe context.

Any thoughts?

**Comment by danyao** [comment]
I ran into the same question, and got this answer from @jpchase 

> Yes, assuming it's iframe with src="some cross origin url", and the response from that url provides a matching token.
> Origin trials are not inherited in frames. Each document/frame/execution context must enable a trial independently
