### ISSUE TITLE
Limitation of use of third-party token

### ISSUE THREAD

**Issue by shigeki** [jpchase/ExperimentalFramework#75]
It seems that a third-party token can not be valid as the wrong origin when it is written in the document as the first-party origin token.

If so, please clarify it in the FAQ that the third-party token can be used only loaded from the script.

**Comment by dpierangeli** [comment]
The script can be loaded only from the origin chosen at the request time?

**Comment by shigeki** [comment]
Thanks for your comment. 
This issue was really old, about two and half years ago, and I'm no longer working on this. So close this.
